/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/active-workout`; params?: Router.UnknownInputParams; } | { pathname: `/exercise-library`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/list-users`; params?: Router.UnknownInputParams; } | { pathname: `/manage-exercises`; params?: Router.UnknownInputParams; } | { pathname: `/manage-students`; params?: Router.UnknownInputParams; } | { pathname: `/manage-workouts`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/select-workout`; params?: Router.UnknownInputParams; } | { pathname: `/setup-profile`; params?: Router.UnknownInputParams; } | { pathname: `/student-workouts`; params?: Router.UnknownInputParams; } | { pathname: `/template-exercises`; params?: Router.UnknownInputParams; } | { pathname: `/workout-templates`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workouts` | `/workouts`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/active-workout`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise-library`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/list-users`; params?: Router.UnknownOutputParams; } | { pathname: `/manage-exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/manage-students`; params?: Router.UnknownOutputParams; } | { pathname: `/manage-workouts`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/select-workout`; params?: Router.UnknownOutputParams; } | { pathname: `/setup-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/student-workouts`; params?: Router.UnknownOutputParams; } | { pathname: `/template-exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/workout-templates`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workouts` | `/workouts`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/active-workout${`?${string}` | `#${string}` | ''}` | `/exercise-library${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/list-users${`?${string}` | `#${string}` | ''}` | `/manage-exercises${`?${string}` | `#${string}` | ''}` | `/manage-students${`?${string}` | `#${string}` | ''}` | `/manage-workouts${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/select-workout${`?${string}` | `#${string}` | ''}` | `/setup-profile${`?${string}` | `#${string}` | ''}` | `/student-workouts${`?${string}` | `#${string}` | ''}` | `/template-exercises${`?${string}` | `#${string}` | ''}` | `/workout-templates${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workouts${`?${string}` | `#${string}` | ''}` | `/workouts${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/active-workout`; params?: Router.UnknownInputParams; } | { pathname: `/exercise-library`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/list-users`; params?: Router.UnknownInputParams; } | { pathname: `/manage-exercises`; params?: Router.UnknownInputParams; } | { pathname: `/manage-students`; params?: Router.UnknownInputParams; } | { pathname: `/manage-workouts`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/select-workout`; params?: Router.UnknownInputParams; } | { pathname: `/setup-profile`; params?: Router.UnknownInputParams; } | { pathname: `/student-workouts`; params?: Router.UnknownInputParams; } | { pathname: `/template-exercises`; params?: Router.UnknownInputParams; } | { pathname: `/workout-templates`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workouts` | `/workouts`; params?: Router.UnknownInputParams; };
    }
  }
}
